
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: wizeworks-encrypt
  namespace: wizeworks
spec:
  acme:
    email: support@jobsight.co
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: wizeworks-encrypt-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wize-content-ingress
  namespace: wizeworks
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: wizeworks-encrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.wize.works
      secretName: wize-content-tls
  rules:
    - host: api.wize.works
      http:
        paths:
          - path: /wize-content(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: wize-content-service
                port:
                  number: 80